---
title: "hmwave_demo_1"
output: html_notebook
---


## Load packages and helper functions
```{r}

library(lhs)
library(DiceKriging)
#source('https://raw.githubusercontent.com/dougmcneall/packages-git/5f79ffe749f25c6fc39f4f7925e1538d36b7caf1/emtools.R')
#source('https://raw.githubusercontent.com/dougmcneall/packages-git/5f79ffe749f25c6fc39f4f7925e1538d36b7caf1/imptools.R')
#source('https://raw.githubusercontent.com/dougmcneall/packages-git/5f79ffe749f25c6fc39f4f7925e1538d36b7caf1/vistools.R')

source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/emtools.R")
source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/imptools.R")
source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/vistools.R")

source('hmwave_demo_0.fun.R')
```



### initial design  
Set up an initial design, sampling sparsely from the input domain (as if the model was expensive to run).  
Experiment with n (initial design points), n.app (number of points to augment the design with in each wave), and uncertainty budget.

```{r}
n = 10 # number of initial design points
k = 4  # number of model inputs
d = 3  # number of model outputs

# simplest method is to choose a subset of the discovered NROY
# points to append to the design

n.app = 10 # number of points to append

X = maximinLHS(n, k = k,dup = 2)
colnames(X) <- c('x1', 'x2', 'x3', 'x4')

#X.target = matrix(runif(4), nrow = 1) # uncomment this and comment the next line for a random target input.
X.target = matrix(rep(0.5,4), nrow = 1)

# run the model outside of the function
#Y = run.model(X)
#Y.target = run.model(X.target)

```


```{r}

Y.raw = run.model(X)
Y.target.raw = run.model(X.target)

Y.all.norm = normalize(rbind(Y.raw, Y.target.raw))
Y = Y.all.norm[1:n, ]
Y.target = matrix(Y.all.norm[n+1, ], nrow = 1)
```


```{r}
# Assume the entire uncertainty budget is in the observational uncertainty initially
#obs.sd.list = list(0.013,0.013,0.013)
# at around 0.01, the HM breaks, putting the I of the target point above 3
obs.sd.list = list(0.01,0.01,0.01)
disc.list = list(0,0,0) 
disc.sd.list = list(0, 0, 0) 

thres = 3   # implausibility threshold

mins.aug = rep(0,4)
maxes.aug = rep(1,4)

# Improvements to the above function from Andrianakis et al. (2015)
# 1) Reduce the range the emulator is fit over, as the waves continue.
# 2) Sample candidate design points from NEAR the existing NROY design points.
```

```{r}
addNroyDesignPoints = function(X, Y, Y.target, n.aug,
                                  mins.aug, maxes.aug,
                                  thres = 3, disc.list,
                                  disc.sd.list, obs.sd.list){
  
  # Add NROY design points to a design, using uniform sampling from the
  # entire input space.
  # Inputs
  # X            ...       design matrix (output from maximinLHS)    
  # Y            ...       model output matrix
  # Y.target     ...       Target output, or "observation"
  # n.aug        ...       number of candidate points to augment the lhs
  # mins.aug
  # maxes.aug    ...       Limits on the candidate points
  
  # list of fitted km objects, one list element for each output
  fit.list = create.kmfit.list(X=X, Y=Y)
  
  # How good is the fit?
  loo.list = lapply(fit.list, FUN = leaveOneOut.km, type = 'UK', trend.reestim = TRUE)
  
  loo.mse.vec = rep(NA, length(loo.list))
  for(i in 1:length(loo.list)){
    
    loo.mse = mean((loo.list[[i]]$mean - Y.target[,i])^2)
    loo.mse.vec[i] = loo.mse
  }
  
  # create a new set of candidate points
  #X.aug = augmentLHS(X, n.aug) # this will add to the current design.
  X.aug = samp.unif(n.aug, mins = mins.aug, maxes = maxes.aug)
  colnames(X.aug) = colnames(X)
  
  # predicting the output at each design point
  pred.list = lapply(fit.list, FUN = 'predict', newdata = X.aug, type = 'UK')
  # calculate the implausibility at each design point
  
  impl.mat = NULL
  for(i in 1:length(pred.list)){
    
    pred.impl = impl(em = pred.list[[i]]$mean,
                     em.sd = pred.list[[i]]$sd,
                     disc = disc.list[[i]],
                     disc.sd = disc.sd.list[[i]],
                     obs = Y.target[[i]],
                     obs.sd = obs.sd.list[[i]])
    
    impl.mat = cbind(impl.mat, pred.impl)
  }
  
  # Which of the candidte design points are NROY?
  
  # create a matrix of the implausibility measures
  # find the indices of the matrix where all are below the threshold.
  nroy.tf = apply(impl.mat, 1, FUN = all.bt, thres = thres)
  nroy.ix = which(nroy.tf==TRUE)
  X.nroy = X.aug[nroy.ix, ]
  
  # I think this code was wrong
  X.nroy.max = apply(X.nroy, 2, max)
  X.nroy.min = apply(X.nroy, 2, min)
  
  return(list(X.nroy = X.nroy,
              X.aug = X.aug, 
              impl.mat = impl.mat, 
              loo.mse.vec = loo.mse.vec,
              fit.list = fit.list,
              pred.list = pred.list,
              X.nroy.max = X.nroy.max,
              X.nroy.min = X.nroy.min,
              X = X,
              Y = Y)
  )
}

```


```{r}

# This function augments the original design with points that are 
# found to be NROY using the emulator. It samples uniformly across the original space,
# and then keeps n.aug points.
wave1 = addNroyDesignPoints(X = X, 
                               Y = Y, 
                               Y.target = Y.target,
                               n.aug = 100000, 
                               mins.aug = mins.aug,
                               maxes.aug = maxes.aug,
                               thres = 3,
                               disc.list=disc.list,
                               disc.sd.list = disc.sd.list,
                               obs.sd.list = obs.sd.list)

# This part excludes any original design points outside of the ranges returned as NROY by
# add.nroy.design.points. This shrinks down the domain that the emulator
# is fit over.
keep1.ix = which(apply(X, FUN = WithinRange,1,
                      maxes = wave1$X.nroy.max,
                      mins = wave1$X.nroy.min))

# This part takes the n.aug points found to be NROY, and chooses n.app of them that are found to be
# furthest apart. These are appended to the design points that are inside the marginal NROY ranges. 
X2 = rbind(X[keep1.ix, ] , ChooseMaximinNroy(n.app = n.app, waveobj=wave1, nreps = 10000))

# Run the model at the new design
Y2.raw = run.model(X2)

# Normalise with respect to the original output.
Y2 = normalize(Y2.raw, wrt = Y.raw)

```

```{r}

getEmulatorPostVar = function(waveobj){
  # Returns the min, mean and max emulator posterior variance for a wave,
  # for each output
  # 
  n = nrow(waveobj$X.aug)
  p = length(waveobj$pred.list)
  
  pv.mat = matrix(ncol = p , nrow = n)
  
  for(i in 1:p){
    pv.mat[, i]  =   (waveobj$pred.list[[i]]$sd)^2
    
  }
  pv.mean = apply(pv.mat,2, mean)
  pv.max = apply(pv.mat, 2, max)
  pv.min = apply(pv.mat,2, min)
  
  
  return(list(pv.mat = pv.mat, pv.mean = pv.mean, pv.min = pv.min, pv.max = pv.max) )           
}

```


```{r}

loopAddDesignPoint = function(X, 
                              Y, 
                              Y.target, 
                              n.aug,
                              mins.aug,
                              maxes.aug,
                              thres = 3, 
                              disc.list,
                              disc.sd.list,
                              obs.sd.list,
                              waves = 3,
                              n.app = n.app,
                              nreps = 1000,
                              shrink = TRUE){
  
  if(length(n.aug) ==1){
    n.aug = rep(n.aug, waves)
  }
  
  wavelist = vector(mode='list', length = waves)
  Xlist  = vector(mode='list', length = waves)
  Ylist  = vector(mode='list', length = waves)
  
  for(i in 1:waves){
    
    wave = addNroyDesignPoints(X = X, 
                                  Y = Y, 
                                  Y.target = Y.target,
                                  n.aug = n.aug[i], 
                                  mins.aug = mins.aug,
                                  maxes.aug = maxes.aug,
                                  thres = thres,
                                  disc.list=disc.list,
                                  disc.sd.list = disc.sd.list,
                                  obs.sd.list = obs.sd.list)
    
    # This part excludes any original design points outside of the ranges returned as NROY by
    # add.nroy.design.points. This shrinks down the domain that the emulator
    # is fit over.
    
    if(shrink){
      keep.ix = which(apply(X, FUN = WithinRange,1,
                             maxes = wave$X.nroy.max,
                             mins = wave$X.nroy.min))
      
      # This part takes the n.aug points found to be NROY, 
      # and chooses n.app of them that are found to be furthest apart. 
      # These are appended to the design points that are inside the marginal NROY ranges. 
      
      Xnew = rbind(X[keep.ix, ] , ChooseMaximinNroy(n.app = n.app, waveobj=wave, nreps = nreps))
      
    }
    
    else{
      Xnew = rbind(X, ChooseMaximinNroy(n.app = n.app, waveobj = wave, nreps = nreps) )
    }
    
    # Run the model at the new design
    Ynew.raw = run.model(Xnew)
    
    # Normalise with respect to the original output.
    Ynew = normalize(Ynew.raw, wrt = Ynew.raw)
    
    X = Xnew
    Y = Ynew
    
    wavelist[[i]] = wave
    Xlist[[i]] = X
    Ylist[[i]] = Y
    
    
  }
  
  return(list(wavelist = wavelist, shrink = shrink, Xlist = Xlist, Ylist = Ylist, nreps = nreps))
}
```


```{r, echo = FALSE, results = 'hide', message=FALSE, hide=TRUE}

# Increase n.aug as you go through the waves
n.aug = c(100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000)

test = loopAddDesignPoint (X = X, 
                               Y = Y, 
                               Y.target = Y.target,
                               n.aug = n.aug, 
                               mins.aug = mins.aug,
                               maxes.aug = maxes.aug,
                               thres = 3,
                               disc.list=disc.list,
                               disc.sd.list = disc.sd.list,
                               obs.sd.list = obs.sd.list,
                           n.app = n.app,
                           waves = 8,
                           shrink = TRUE
)

```


How does the emulator mean compare to the uncertainty of the observations?
```{r}

pv.mat = NULL

for(i in 1:length(test$wavelist)){
 
pv.mat =  rbind(pv.mat, getEmulatorPostVar(test$wavelist[[i]])$pv.mean )
   
}
#pv.mat

matplot(pv.mat, type = 'o', main = 'mean emulator posterior variance', 
        col = c('black', 'red', 'blue'), log = 'y', lty = 'solid', pch = 19)

abline(h = (unlist(obs.sd.list))^2, col = c('black', 'red', 'blue'), lty = 'dashed')

```

```{r, fig.width = 8, fig.height = 8}

for(i in 1:length(test$wavelist)){
  
  x = rbind(test$wavelist[[i]]$X.nroy, test$Xlist[[i]], X.target)
  
  par(oma = c(0,0,0,3), bg = 'white')
  cols = c(rep('darkgrey', nrow(test$wavelist[[i]]$X.nroy)),
          rep('blue', nrow(test$Xlist[[i]])),
          'red')
 
  pairs(x,
        gap = 0, lower.panel = NULL, xlim = c(0,1), ylim = c(0,1),
        cex.labels = 3,
        col.axis = 'white',
        col = cols,
        pch = 19,
        cex = c(rep(1, nrow(x)-1), 2)
        )
}
reset()
legend('bottom',
       legend = c('NROY samples', 'Design points', 'True input (hidden)'),
       col = c('darkgrey', 'blue', 'red'),
       inset = 0.05,
       cex = 1.1,
       pch = 19
       )




```

```{r, fig.width = 8, fig.height = 8}

for(i in 1:length(test$wavelist)){
  
  x = rbind(test$wavelist[[i]]$X.nroy, X.target)
  
  par(oma = c(0,0,0,3), bg = 'white')
  pairs(x,
        gap = 0, lower.panel = NULL, xlim = c(0,1), ylim = c(0,1),
        panel = dfunc.up.truth,
        cex.labels = 3,
        col.axis = 'white')
}

```


```{r}

GetNroyProp = function(waveobj){
  nrow(waveobj$X.nroy) / nrow(waveobj$X.aug)
}

wave.prop = sapply(test$wavelist, FUN = GetNroyProp)

par(las = 1)
plot(1:length(test$wavelist), wave.prop * 100, type = 'b',
     xlab = 'Wave', ylab = 'NROY proportion (%)', log = 'y')


```


```{r}

# How much of the initial input space is covered by our NROY space?
# With the "shrink = TRUE" option, we're not uniformly sampling from
# the entire unit cube in the first place. 

# Functions to find the size (compared to the unit cube)
# of the parameter space cuboid that we are sampling from
getRangeMat = function(X){
  
 r =  apply(X, 2, range)
 r
}


getVolProp = function(X){
  # Get the proportion of the space, compared to the unit cube
  rm = getRangeMat(X)
  rv = rm[2,] - rm[1,]
  out = tail(cumprod(rv),1)
  out
}

#testmat = matrix(c(0,0,0,0.9,0.9,0.9), nrow = 2, byrow = TRUE)
#getVolProp(testmat)

# for each wave, find the proportion of the unit cube that was initially sampled.
# The final proportion of NROY space is just the proportion of that.
# This might be important when 

getNROYprop = function(waveobj){
  
    # Finds the proportion of NROY space, but corrects by the
    # volume of space initially sampled (assuming marginal limits)
  
  # first, find the proportion of the unit cube that was sampled
  vp = getVolProp(waveobj$X.aug)
  
  # Then find the proportion of NROY points from that sample
  np = (nrow(waveobj$X.nroy)) / (nrow(waveobj$X.aug))
  
  # Then multiply the two together.
  out = vp * np
  
  out
}

nroy.prop = sapply(test$wavelist, getNROYprop)

par(las = 1)
plot(1:length(test$wavelist), nroy.prop * 100, type = 'b',
     xlab = 'Wave', ylab = 'NROY proportion (%)', log = 'y')

  
  
```

```{r, message=FALSE,warning=FALSE}
# What is the implausibility of the genuine point? 
# Apply this over the waves and see how it moves about

waves_list = test$wavelist

target.impl.mat = matrix(ncol = ncol(Y), nrow = length(waves_list))
colnames(target.impl.mat) <- colnames(Y)

for(j in 1:length(waves_list)){
  
 waveobj = waves_list[[j]]
 
 X.target.pred.list = lapply(waveobj$fit.list, FUN = 'predict', newdata =matrix(X.target, nrow = 1), type = 'UK')
  
  impl.row= NULL
  for(i in 1:length(X.target.pred.list)){
    
    pred.impl = impl(em = X.target.pred.list[[i]]$mean,
                     em.sd = X.target.pred.list[[i]]$sd,
                     disc = disc.list[[i]],
                     disc.sd = disc.sd.list[[i]],
                     obs = Y.target[[i]],
                     obs.sd = obs.sd.list[[i]])
    
    impl.row = cbind(impl.row, pred.impl)
  }
  
  target.impl.mat[j, ] = impl.row
  
}

par(las = 1)
matplot(target.impl.mat, type = 'l', lty = 'solid', xlab = 'Wave', ylab = 'Implausibility',
        col = c('black', 'red', 'blue'), main = 'implausibility of target input')
abline(h = 3, lty = 'dashed', col = 'grey')
legend('topleft', legend = c('y1','y2','y3'),lty = 'solid', col = c('black', 'red', 'blue'))
```


